export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
//export const MODAL_SUBMIT = 'MODAL_SUBMIT';
//export const MODAL_SUBMIT_SUCCESS = 'MODAL_SUBMIT';
export const SETTINGS_GET_SUCCESS = 'SETTINGS_GET_SUCCESS';
export const SETTINGS_GET_ERROR = 'SETTINGS_GET_ERROR';
export const SETTINGS_UPDATE_SUCCESS = 'SETTINGS_UPDATE_SUCCESS';
export const SETTINGS_UPDATE_ERROR = 'SETTINGS_UPDATE_ERROR';